---
# Chris UI using Podman

apiVersion: apps/v1

kind: Deployment
metadata:
  name: minichris-chrisui
  labels:
    app.kubernetes.io/name: minichris-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: miniChRIS
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minichris-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minichris-ui
    spec:
      containers:
        - name: chrisui
          image: ghcr.io/fnndsc/chris_ui:4b813b0
          ports:
          - containerPort: 80
            hostPort: 8020
          env:
            - name: CHRIS_UI_URL
              value: http://localhost:8000/api/v1/
            - name: PFDCM_URL
              value: http://localhost:4005/
