# Test miniChRIS-podman with miniChRIS-docker's test suite

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-podman:
    runs-on: ubuntu-24.04
    steps:
      - name: Start Podman Daemon
        run: systemctl --user start podman.service
      - name: Podman Info
        run: podman info
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start CUBE
        run: ./minichris.sh up

      - name: Checkout miniChRIS-docker
        uses: actions/checkout@v4
        with:
          repository: FNNDSC/miniChRIS-docker
          path: ./miniChRIS-docker
          ref: next
      - name: Test
        run: |
          set +e
          ./miniChRIS-docker/test.sh
          rc=$?
          
          # if tests fail, print out all logs
          if [ "$rc" != '0' ]; then
            set -x
            for c in $(podman ps -a --format '{{ .Names }}' --filter 'name=minichris'); do
              podman logs $c
            done
          fi

          exit $rc
      - name: Stop CUBE
        run: ./minichris.sh down
